APP_NAME = "Pakistan Citizen AI Agent"

APP_VERSION = "1.0.0"

DEFAULT_MAX_SEARCH_RESULTS = 8

DEFAULT_MAX_OFFICIAL_RESULTS = 5

SEARCH_TIMEOUT = 15

GROQ_MODEL = "openai/gpt-oss-120b"

MINIMUM_USEFUL_SOURCES = 1
